/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDerivRouteImport } from './routes/auth.deriv'
import { Route as ApiExportZipRouteImport } from './routes/api.export.zip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDerivRoute = AuthDerivRouteImport.update({
  id: '/auth/deriv',
  path: '/auth/deriv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportZipRoute = ApiExportZipRouteImport.update({
  id: '/api/export/zip',
  path: '/api/export/zip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/deriv': typeof AuthDerivRoute
  '/api/export/zip': typeof ApiExportZipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/deriv': typeof AuthDerivRoute
  '/api/export/zip': typeof ApiExportZipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/deriv': typeof AuthDerivRoute
  '/api/export/zip': typeof ApiExportZipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/deriv' | '/api/export/zip'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/deriv' | '/api/export/zip'
  id: '__root__' | '/' | '/auth/deriv' | '/api/export/zip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthDerivRoute: typeof AuthDerivRoute
  ApiExportZipRoute: typeof ApiExportZipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/deriv': {
      id: '/auth/deriv'
      path: '/auth/deriv'
      fullPath: '/auth/deriv'
      preLoaderRoute: typeof AuthDerivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/zip': {
      id: '/api/export/zip'
      path: '/api/export/zip'
      fullPath: '/api/export/zip'
      preLoaderRoute: typeof ApiExportZipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthDerivRoute: AuthDerivRoute,
  ApiExportZipRoute: ApiExportZipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
